name = "Ramenlikkers Pack"
author = "Joris"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8d6688f863390bef7188a3feaa885080564cb5c5cd2c0afcba63a0cc10e3d27"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
