name: Build and Publish
on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout modpack repo
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Packwiz
        run: |
          go install github.com/packwiz/packwiz@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
          packwiz --help

      - name: Set version in pack.toml
        run: |
          sed -i "s/^version = .*/version = \"${{ github.event.release.tag_name }}\"/" pack.toml

      - name: Build .mrpack with Packwiz
        run: |
          mkdir -p dist
          packwiz modrinth export \
            --output "dist/ramenlikkers-pack-${{ github.event.release.tag_name }}.mrpack"

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: modpack
          path: dist/*.mrpack

      - name: Upload to Modrinth
        uses: RubixDev/modrinth-upload@v1
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          file_path: dist/*.mrpack
          name: Ramenlikkers Pack ${{ github.event.release.tag_name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          game_versions: 1.21.10
          loaders: fabric
          release_type: beta
          featured: true
          project_id: HDlvGK5r
